name = "luciole"
version = "0.1.5"
target = "javascript"
description = "An API for writting Cypress tests in Gleam."
licences = ["MIT"]
repository = { type = "github", user = "steerlab", repo = "luciole", path = "api" }

# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
simplifile = ">= 2.2.1 and < 3.0.0"
glance = ">= 5.0.0 and < 6.0.0"
gleam_javascript = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.3.1 and < 2.0.0"
